/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Account : AccountBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	// Please inherit and implement "class Account : AccountBase"
	public abstract class AccountBase : Entity
	{
		public EntityBaseEntityCall_AccountBase baseEntityCall = null;
		public EntityCellEntityCall_AccountBase cellEntityCall = null;

		public UInt32 goldBase = 0;
		public virtual void onGoldBaseChanged(UInt32 oldValue) {}
		public Byte index = 0;
		public virtual void onIndexChanged(Byte oldValue) {}
		public Byte isReady = 0;
		public virtual void onIsReadyChanged(Byte oldValue) {}
		public string playernameBase = "";
		public virtual void onPlayernameBaseChanged(string oldValue) {}
		public string playernameCell = "";
		public virtual void onPlayernameCellChanged(string oldValue) {}

		public abstract void onJoinRoom(Byte arg1); 
		public abstract void onLeaveRoom(); 

		public AccountBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AccountBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AccountBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Account"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 13:
					Byte onJoinRoom_arg1 = stream.readUint8();
					onJoinRoom(onJoinRoom_arg1);
					break;
				case 14:
					onLeaveRoom();
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Account"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 2:
						UInt32 oldval_goldBase = goldBase;
						goldBase = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onGoldBaseChanged(oldval_goldBase);
						}
						else
						{
							if(inWorld)
								onGoldBaseChanged(oldval_goldBase);
						}

						break;
					case 4:
						Byte oldval_index = index;
						index = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIndexChanged(oldval_index);
						}
						else
						{
							if(inWorld)
								onIndexChanged(oldval_index);
						}

						break;
					case 5:
						Byte oldval_isReady = isReady;
						isReady = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onIsReadyChanged(oldval_isReady);
						}
						else
						{
							if(inWorld)
								onIsReadyChanged(oldval_isReady);
						}

						break;
					case 1:
						string oldval_playernameBase = playernameBase;
						playernameBase = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onPlayernameBaseChanged(oldval_playernameBase);
						}
						else
						{
							if(inWorld)
								onPlayernameBaseChanged(oldval_playernameBase);
						}

						break;
					case 3:
						string oldval_playernameCell = playernameCell;
						playernameCell = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onPlayernameCellChanged(oldval_playernameCell);
						}
						else
						{
							if(inWorld)
								onPlayernameCellChanged(oldval_playernameCell);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Account"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			UInt32 oldval_goldBase = goldBase;
			Property prop_goldBase = pdatas[4];
			if(prop_goldBase.isBase())
			{
				if(inited && !inWorld)
					onGoldBaseChanged(oldval_goldBase);
			}
			else
			{
				if(inWorld)
				{
					if(prop_goldBase.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGoldBaseChanged(oldval_goldBase);
					}
				}
			}

			Byte oldval_index = index;
			Property prop_index = pdatas[5];
			if(prop_index.isBase())
			{
				if(inited && !inWorld)
					onIndexChanged(oldval_index);
			}
			else
			{
				if(inWorld)
				{
					if(prop_index.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIndexChanged(oldval_index);
					}
				}
			}

			Byte oldval_isReady = isReady;
			Property prop_isReady = pdatas[6];
			if(prop_isReady.isBase())
			{
				if(inited && !inWorld)
					onIsReadyChanged(oldval_isReady);
			}
			else
			{
				if(inWorld)
				{
					if(prop_isReady.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onIsReadyChanged(oldval_isReady);
					}
				}
			}

			string oldval_playernameBase = playernameBase;
			Property prop_playernameBase = pdatas[7];
			if(prop_playernameBase.isBase())
			{
				if(inited && !inWorld)
					onPlayernameBaseChanged(oldval_playernameBase);
			}
			else
			{
				if(inWorld)
				{
					if(prop_playernameBase.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPlayernameBaseChanged(oldval_playernameBase);
					}
				}
			}

			string oldval_playernameCell = playernameCell;
			Property prop_playernameCell = pdatas[8];
			if(prop_playernameCell.isBase())
			{
				if(inited && !inWorld)
					onPlayernameCellChanged(oldval_playernameCell);
			}
			else
			{
				if(inWorld)
				{
					if(prop_playernameCell.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPlayernameCellChanged(oldval_playernameCell);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
}