/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;



	public class DATATYPE_PlayerList : DATATYPE_BASE
	{
		public PlayerList createFromStreamEx(MemoryStream stream)
		{
			UInt32 size = stream.readUint32();
			PlayerList datas = new PlayerList();

			while(size > 0)
			{
				--size;
				datas.Add(stream.readEntitycall());
			};

			return datas;
		}

		public void addToStreamEx(Bundle stream, PlayerList v)
		{
			stream.writeUint32((UInt32)v.Count);
			for(int i=0; i<v.Count; ++i)
			{
				stream.writeEntitycall(v[i]);
			};
		}
	}


}