/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_goldBase = new Property();
			pAccount_goldBase.name = "goldBase";
			pAccount_goldBase.properUtype = 2;
			pAccount_goldBase.properFlags = 32;
			pAccount_goldBase.aliasID = 4;
			UInt32 Account_goldBase_defval;
			UInt32.TryParse("", out Account_goldBase_defval);
			pAccount_goldBase.defaultVal = Account_goldBase_defval;
			pAccountModule.propertys["goldBase"] = pAccount_goldBase; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_goldBase.aliasID] = pAccount_goldBase;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(goldBase / 2).");

			Property pAccount_index = new Property();
			pAccount_index.name = "index";
			pAccount_index.properUtype = 4;
			pAccount_index.properFlags = 4;
			pAccount_index.aliasID = 5;
			Byte Account_index_defval;
			Byte.TryParse("", out Account_index_defval);
			pAccount_index.defaultVal = Account_index_defval;
			pAccountModule.propertys["index"] = pAccount_index; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_index.aliasID] = pAccount_index;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(index / 4).");

			Property pAccount_isReady = new Property();
			pAccount_isReady.name = "isReady";
			pAccount_isReady.properUtype = 5;
			pAccount_isReady.properFlags = 4;
			pAccount_isReady.aliasID = 6;
			Byte Account_isReady_defval;
			Byte.TryParse("0", out Account_isReady_defval);
			pAccount_isReady.defaultVal = Account_isReady_defval;
			pAccountModule.propertys["isReady"] = pAccount_isReady; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_isReady.aliasID] = pAccount_isReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(isReady / 5).");

			Property pAccount_playernameBase = new Property();
			pAccount_playernameBase.name = "playernameBase";
			pAccount_playernameBase.properUtype = 1;
			pAccount_playernameBase.properFlags = 32;
			pAccount_playernameBase.aliasID = 7;
			string Account_playernameBase_defval = "";
			pAccount_playernameBase.defaultVal = Account_playernameBase_defval;
			pAccountModule.propertys["playernameBase"] = pAccount_playernameBase; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playernameBase.aliasID] = pAccount_playernameBase;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playernameBase / 1).");

			Property pAccount_playernameCell = new Property();
			pAccount_playernameCell.name = "playernameCell";
			pAccount_playernameCell.properUtype = 3;
			pAccount_playernameCell.properFlags = 4;
			pAccount_playernameCell.aliasID = 8;
			string Account_playernameCell_defval = "";
			pAccount_playernameCell.defaultVal = Account_playernameCell_defval;
			pAccountModule.propertys["playernameCell"] = pAccount_playernameCell; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playernameCell.aliasID] = pAccount_playernameCell;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playernameCell / 3).");

			List<DATATYPE_BASE> pAccount_onJoinRoom_args = new List<DATATYPE_BASE>();
			pAccount_onJoinRoom_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_onJoinRoom = new Method();
			pAccount_onJoinRoom.name = "onJoinRoom";
			pAccount_onJoinRoom.methodUtype = 13;
			pAccount_onJoinRoom.aliasID = 1;
			pAccount_onJoinRoom.args = pAccount_onJoinRoom_args;

			pAccountModule.methods["onJoinRoom"] = pAccount_onJoinRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onJoinRoom.aliasID] = pAccount_onJoinRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onJoinRoom / 13).");

			List<DATATYPE_BASE> pAccount_onLeaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_onLeaveRoom = new Method();
			pAccount_onLeaveRoom.name = "onLeaveRoom";
			pAccount_onLeaveRoom.methodUtype = 14;
			pAccount_onLeaveRoom.aliasID = 2;
			pAccount_onLeaveRoom.args = pAccount_onLeaveRoom_args;

			pAccountModule.methods["onLeaveRoom"] = pAccount_onLeaveRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onLeaveRoom.aliasID] = pAccount_onLeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onLeaveRoom / 14).");

			List<DATATYPE_BASE> pAccount_addGold_args = new List<DATATYPE_BASE>();

			Method pAccount_addGold = new Method();
			pAccount_addGold.name = "addGold";
			pAccount_addGold.methodUtype = 6;
			pAccount_addGold.aliasID = -1;
			pAccount_addGold.args = pAccount_addGold_args;

			pAccountModule.methods["addGold"] = pAccount_addGold; 
			pAccountModule.base_methods["addGold"] = pAccount_addGold;

			pAccountModule.idbase_methods[pAccount_addGold.methodUtype] = pAccount_addGold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(addGold / 6).");

			List<DATATYPE_BASE> pAccount_createRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_createRoom = new Method();
			pAccount_createRoom.name = "createRoom";
			pAccount_createRoom.methodUtype = 7;
			pAccount_createRoom.aliasID = -1;
			pAccount_createRoom.args = pAccount_createRoom_args;

			pAccountModule.methods["createRoom"] = pAccount_createRoom; 
			pAccountModule.base_methods["createRoom"] = pAccount_createRoom;

			pAccountModule.idbase_methods[pAccount_createRoom.methodUtype] = pAccount_createRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(createRoom / 7).");

			List<DATATYPE_BASE> pAccount_enterMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_enterMatch = new Method();
			pAccount_enterMatch.name = "enterMatch";
			pAccount_enterMatch.methodUtype = 9;
			pAccount_enterMatch.aliasID = -1;
			pAccount_enterMatch.args = pAccount_enterMatch_args;

			pAccountModule.methods["enterMatch"] = pAccount_enterMatch; 
			pAccountModule.base_methods["enterMatch"] = pAccount_enterMatch;

			pAccountModule.idbase_methods[pAccount_enterMatch.methodUtype] = pAccount_enterMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(enterMatch / 9).");

			List<DATATYPE_BASE> pAccount_joinRoom_args = new List<DATATYPE_BASE>();
			pAccount_joinRoom_args.Add(EntityDef.id2datatypes[3]);

			Method pAccount_joinRoom = new Method();
			pAccount_joinRoom.name = "joinRoom";
			pAccount_joinRoom.methodUtype = 8;
			pAccount_joinRoom.aliasID = -1;
			pAccount_joinRoom.args = pAccount_joinRoom_args;

			pAccountModule.methods["joinRoom"] = pAccount_joinRoom; 
			pAccountModule.base_methods["joinRoom"] = pAccount_joinRoom;

			pAccountModule.idbase_methods[pAccount_joinRoom.methodUtype] = pAccount_joinRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(joinRoom / 8).");

			List<DATATYPE_BASE> pAccount_reqSetPlayername_args = new List<DATATYPE_BASE>();
			pAccount_reqSetPlayername_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqSetPlayername = new Method();
			pAccount_reqSetPlayername.name = "reqSetPlayername";
			pAccount_reqSetPlayername.methodUtype = 5;
			pAccount_reqSetPlayername.aliasID = -1;
			pAccount_reqSetPlayername.args = pAccount_reqSetPlayername_args;

			pAccountModule.methods["reqSetPlayername"] = pAccount_reqSetPlayername; 
			pAccountModule.base_methods["reqSetPlayername"] = pAccount_reqSetPlayername;

			pAccountModule.idbase_methods[pAccount_reqSetPlayername.methodUtype] = pAccount_reqSetPlayername;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqSetPlayername / 5).");

			ScriptModule pRoomModule = new ScriptModule("Room");
			EntityDef.moduledefs["Room"] = pRoomModule;
			EntityDef.idmoduledefs[3] = pRoomModule;

			Property pRoom_position = new Property();
			pRoom_position.name = "position";
			pRoom_position.properUtype = 40000;
			pRoom_position.properFlags = 4;
			pRoom_position.aliasID = 1;
			Vector3 Room_position_defval = new Vector3();
			pRoom_position.defaultVal = Room_position_defval;
			pRoomModule.propertys["position"] = pRoom_position; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_position.aliasID] = pRoom_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(position / 40000).");

			Property pRoom_direction = new Property();
			pRoom_direction.name = "direction";
			pRoom_direction.properUtype = 40001;
			pRoom_direction.properFlags = 4;
			pRoom_direction.aliasID = 2;
			Vector3 Room_direction_defval = new Vector3();
			pRoom_direction.defaultVal = Room_direction_defval;
			pRoomModule.propertys["direction"] = pRoom_direction; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_direction.aliasID] = pRoom_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(direction / 40001).");

			Property pRoom_spaceID = new Property();
			pRoom_spaceID.name = "spaceID";
			pRoom_spaceID.properUtype = 40002;
			pRoom_spaceID.properFlags = 16;
			pRoom_spaceID.aliasID = 3;
			UInt32 Room_spaceID_defval;
			UInt32.TryParse("", out Room_spaceID_defval);
			pRoom_spaceID.defaultVal = Room_spaceID_defval;
			pRoomModule.propertys["spaceID"] = pRoom_spaceID; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_spaceID.aliasID] = pRoom_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(spaceID / 40002).");

			Property pRoom_isPrivate = new Property();
			pRoom_isPrivate.name = "isPrivate";
			pRoom_isPrivate.properUtype = 8;
			pRoom_isPrivate.properFlags = 4;
			pRoom_isPrivate.aliasID = 4;
			Byte Room_isPrivate_defval;
			Byte.TryParse("", out Room_isPrivate_defval);
			pRoom_isPrivate.defaultVal = Room_isPrivate_defval;
			pRoomModule.propertys["isPrivate"] = pRoom_isPrivate; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_isPrivate.aliasID] = pRoom_isPrivate;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(isPrivate / 8).");

			Property pRoom_roomKey = new Property();
			pRoom_roomKey.name = "roomKey";
			pRoom_roomKey.properUtype = 7;
			pRoom_roomKey.properFlags = 4;
			pRoom_roomKey.aliasID = 5;
			UInt16 Room_roomKey_defval;
			UInt16.TryParse("", out Room_roomKey_defval);
			pRoom_roomKey.defaultVal = Room_roomKey_defval;
			pRoomModule.propertys["roomKey"] = pRoom_roomKey; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomKey.aliasID] = pRoom_roomKey;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomKey / 7).");

			pRoomModule.useMethodDescrAlias = true;
			List<DATATYPE_BASE> pRoom_changeIsReady_args = new List<DATATYPE_BASE>();

			Method pRoom_changeIsReady = new Method();
			pRoom_changeIsReady.name = "changeIsReady";
			pRoom_changeIsReady.methodUtype = 20;
			pRoom_changeIsReady.aliasID = -1;
			pRoom_changeIsReady.args = pRoom_changeIsReady_args;

			pRoomModule.methods["changeIsReady"] = pRoom_changeIsReady; 
			pRoomModule.cell_methods["changeIsReady"] = pRoom_changeIsReady;

			pRoomModule.idcell_methods[pRoom_changeIsReady.methodUtype] = pRoom_changeIsReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(changeIsReady / 20).");

			List<DATATYPE_BASE> pRoom_leaveRoom_args = new List<DATATYPE_BASE>();

			Method pRoom_leaveRoom = new Method();
			pRoom_leaveRoom.name = "leaveRoom";
			pRoom_leaveRoom.methodUtype = 19;
			pRoom_leaveRoom.aliasID = -1;
			pRoom_leaveRoom.args = pRoom_leaveRoom_args;

			pRoomModule.methods["leaveRoom"] = pRoom_leaveRoom; 
			pRoomModule.cell_methods["leaveRoom"] = pRoom_leaveRoom;

			pRoomModule.idcell_methods[pRoom_leaveRoom.methodUtype] = pRoom_leaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(leaveRoom / 19).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "Bool";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "RoomKey";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UINT64";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "Gold";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "PlayerList";
				DATATYPE_PlayerList datatype = new DATATYPE_PlayerList();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}