/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void addGold()
		{
			Bundle pBundle = newCall("addGold", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void createRoom()
		{
			Bundle pBundle = newCall("createRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void enterMatch()
		{
			Bundle pBundle = newCall("enterMatch", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void joinRoom(UInt16 arg1)
		{
			Bundle pBundle = newCall("joinRoom", 0);
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			sendCall(null);
		}

		public void reqSetPlayername(string arg1)
		{
			Bundle pBundle = newCall("reqSetPlayername", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
